---
name: "bws-fetch"
description: "Fetch secrets from Bitwarden Secrets Manager into files."
inputs:
  access-token:
    required: true
    description: "BWS access token"
  project-id:
    required: true
    description: "BWS project id"
  secrets:
    required: true
    description: "Comma-separated secret names"
  bws-version:
    required: true
    description: "BWS CLI version"
  bws-sha256:
    required: true
    description: "BWS CLI sha256"
  output-dir:
    required: false
    default: "bws"
    description: "Output directory for secret files"

runs:
  using: "composite"
  steps:
    - name: Install bws CLI
      shell: bash
      run: |
        set -euo pipefail
        umask 077
        version="${{ inputs.bws-version }}"
        checksum="${{ inputs.bws-sha256 }}"
        base_url="https://github.com/mattycramer/sdk-sm/releases/download/gl-bws-cli-v${version}"
        archive="bws-x86_64-unknown-linux-gnu-${version}.tar.gz"
        checksum_file="bws-sha256-checksums-${version}.txt"
        if [ -z "${RUNNER_TEMP:-}" ]; then
          echo "RUNNER_TEMP is not set" >&2
          exit 1
        fi
        tmp_dir="$(mktemp -d "${RUNNER_TEMP}/bws-${version}-XXXXXX")"
        curl --proto '=https' --tlsv1.2 -fL --retry 3 --retry-delay 1 \
          -o "${tmp_dir}/${archive}" "${base_url}/${archive}"
        curl --proto '=https' --tlsv1.2 -fL --retry 3 --retry-delay 1 \
          -o "${tmp_dir}/${checksum_file}" "${base_url}/${checksum_file}"
        expected="$(
          printf '%s\n' \
            'import sys' \
            'checksum_path = sys.argv[1]' \
            'target = sys.argv[2]' \
            'expected = ""' \
            'with open(checksum_path, "r", encoding="utf-8") as handle:' \
            '    for line in handle:' \
            '        line = line.strip()' \
            '        if not line:' \
            '            continue' \
            '        parts = line.split()' \
            '        if len(parts) < 2:' \
            '            continue' \
            '        checksum, name = parts[0], parts[1]' \
            '        if name.startswith("*"):' \
            '            name = name[1:]' \
            '        if name.startswith("./"):' \
            '            name = name[2:]' \
            '        if name == target:' \
            '            expected = checksum' \
            '            break' \
            'if not expected:' \
            '    sys.exit(1)' \
            'print(expected)' \
          | python3 - "${tmp_dir}/${checksum_file}" "${archive}"
        )" || {
          echo "Checksum for ${archive} not found" >&2
          exit 1
        }
        if [ "${expected}" != "${checksum}" ]; then
          echo "Checksum mismatch for ${archive}" >&2
          exit 1
        fi
        printf '%s  %s\n' "${expected}" "${archive}" > "${tmp_dir}/bws.sha256"
        (cd "${tmp_dir}" && sha256sum -c bws.sha256)
        tar -xzf "${tmp_dir}/${archive}" -C "${tmp_dir}"
        bws_path="${tmp_dir}/bws"
        if [ ! -x "${bws_path}" ]; then
          bws_path="$(
            find "${tmp_dir}" -type f -name bws -perm -u+x \
              | head -n 1
          )"
        fi
        if [ -z "${bws_path}" ]; then
          echo "bws binary not found after extraction" >&2
          exit 1
        fi
        chmod 0755 "${bws_path}"
        bws_dir="$(dirname "${bws_path}")"
        echo "${bws_dir}" >> "$GITHUB_PATH"
        echo "BWS_BIN=${bws_path}" >> "$GITHUB_ENV"
        echo "BWS_TMP_DIR=${tmp_dir}" >> "$GITHUB_ENV"
    - name: Fetch secrets
      shell: bash
      env:
        BWS_ACCESS_TOKEN: ${{ inputs.access-token }}
        BWS_PROJECT_ID: ${{ inputs.project-id }}
        SECRETS: ${{ inputs.secrets }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
      run: |
        set -euo pipefail
        access_token_clean="$(printf '%s' "${BWS_ACCESS_TOKEN}" | tr -d '[:space:]')"
        project_id_clean="$(printf '%s' "${BWS_PROJECT_ID}" | tr -d '[:space:]')"
        if [ -z "${access_token_clean}" ]; then
          echo "BWS_ACCESS_TOKEN resolved to empty after normalization" >&2
          exit 1
        fi
        if [ -z "${project_id_clean}" ]; then
          echo "BWS_PROJECT_ID resolved to empty after normalization" >&2
          exit 1
        fi
        secrets_clean="$(printf '%s' "${SECRETS}" | tr -d '[:space:]')"
        if [ -z "${secrets_clean}" ]; then
          echo "SECRETS resolved to empty after normalization" >&2
          exit 1
        fi
        if [ -z "${BWS_BIN:-}" ]; then
          echo "BWS_BIN is not set" >&2
          exit 1
        fi
        BWS_ACCESS_TOKEN="${access_token_clean}" BWS_PROJECT_ID="${project_id_clean}" \
          "${BWS_BIN}" run --project-id "${project_id_clean}" --no-inherit-env -- \
          env SECRETS="${secrets_clean}" OUTPUT_DIR="${OUTPUT_DIR}" \
          GITHUB_ENV="${GITHUB_ENV}" PATH="${PATH}" \
          python3 "${{ github.action_path }}/write_secrets.py"
        if [ -n "${BWS_TMP_DIR:-}" ]; then
          rm -rf "${BWS_TMP_DIR}"
        fi
