name: Prepare BWS app credentials
description: "Load BWS secrets, prepare app credentials, select org, and mint a GitHub App token."
inputs:
  secrets:
    description: "Newline-delimited list of BWS secret names to export"
    required: true
  org_keys:
    description: "Newline-delimited list of org secret keys to map to the matrix org"
    required: true
  github_org:
    description: "GitHub org name for the current matrix entry"
    required: true
  repo:
    description: "Optional single repo name to scope the GitHub App token"
    required: false
    default: ""
  app_id_key:
    description: "Secret name for the GitHub App ID"
    required: false
    default: "GH_ORG_SHARED_APP_ID"
  app_pem_key:
    description: "Secret name for the GitHub App PEM"
    required: false
    default: "GH_ORG_SHARED_APP_PEM"
  chmod_keys:
    description: "Newline-delimited list of secret names to chmod 600"
    required: false
    default: ""
outputs:
  github_app_token_file:
    description: "Path to the minted GitHub App token file"
    value: ${{ steps.store-token.outputs.github_app_token_file }}
runs:
  using: composite
  steps:
    - name: Load BWS secrets to temp files
      shell: bash
      env:
        BWS_ACCESS_TOKEN: ${{ env.BWS_ACCESS_TOKEN }}
        BWS_PROJECT_ID: ${{ env.BWS_PROJECT_ID }}
      run: |
        set -euo pipefail
        if [ -z "${BWS_ACCESS_TOKEN:-}" ] || [ -z "${BWS_PROJECT_ID:-}" ]; then
          printf '%s\n' "BWS_ACCESS_TOKEN and BWS_PROJECT_ID must be set" >&2
          exit 1
        fi
        secrets_dir="${RUNNER_TEMP}/bws"
        mkdir -p "$secrets_dir"
        secrets=()
        while IFS= read -r key; do
          [ -z "$key" ] && continue
          secrets+=("$key")
        done <<'EOF'
        ${{ inputs.secrets }}
        EOF
        if [ "${#secrets[@]}" -eq 0 ]; then
          printf '%s\n' "No secrets provided" >&2
          exit 1
        fi
        bws run --project-id "${BWS_PROJECT_ID:?}" --no-inherit-env -- \
          env SECRETS_DIR="${secrets_dir}" \
          /bin/sh .github/scripts/bws_export_secret_files.sh \
            "${secrets_dir}" \
            "${secrets[@]}"

    - name: Expose secret file paths
      shell: bash
      run: |
        set -euo pipefail
        secrets_dir="${RUNNER_TEMP}/bws"
        skip_keys="$(printf '%s\n' "${{ inputs.org_keys }}" | sed '/^$/d')"
        skip_keys="${skip_keys}
${{ inputs.app_pem_key }}"
        while IFS= read -r key; do
          [ -z "$key" ] && continue
          if printf '%s\n' "$skip_keys" | grep -qx "$key"; then
            continue
          fi
          printf '%s\n' "${key}_FILE=${secrets_dir}/${key}" >> "$GITHUB_ENV"
        done <<'EOF'
        ${{ inputs.secrets }}
        EOF

    - name: Prepare app credentials
      shell: bash
      run: |
        set -euo pipefail
        app_pem_key="${{ inputs.app_pem_key }}"
        app_id_key="${{ inputs.app_id_key }}"
        secrets_dir="${RUNNER_TEMP}/bws"
        src="${secrets_dir}/${app_pem_key}"
        dst="${secrets_dir}/${app_pem_key}.pem"
        umask 077
        if grep -q '\\n' "$src"; then
          data="$(cat "$src")"
          printf '%b' "$data" > "$dst"
        else
          cp "$src" "$dst"
        fi
        chmod 600 "$dst"
        printf '%s\n' "${app_pem_key}_FILE=${dst}" >> "$GITHUB_ENV"
        printf '%s\n' "${app_id_key}_FILE=${secrets_dir}/${app_id_key}" >> "$GITHUB_ENV"
        while IFS= read -r key; do
          [ -z "$key" ] && continue
          chmod 600 "${secrets_dir}/${key}"
        done <<'EOF'
        ${{ inputs.chmod_keys }}
        EOF

    - name: Select org file path
      shell: bash
      run: |
        set -euo pipefail
        matrix_org="${{ inputs.github_org }}"
        secrets_dir="${RUNNER_TEMP}/bws"
        selected=""
        while IFS= read -r key; do
          [ -z "$key" ] && continue
          org_value="$(cat "${secrets_dir}/${key}")"
          if [ "$matrix_org" = "$org_value" ]; then
            printf '%s\n' "${key}_FILE=${secrets_dir}/${key}" >> "$GITHUB_ENV"
            selected="$key"
            break
          fi
        done <<'EOF'
        ${{ inputs.org_keys }}
        EOF
        if [ -z "$selected" ]; then
          printf '%s\n' "Unknown org mapping for ${matrix_org}" >&2
          exit 1
        fi

    - name: Mint GitHub App token (JWT)
      id: app-token
      shell: bash
      run: |
        set -euo pipefail
        app_id_file="${RUNNER_TEMP}/bws/${{ inputs.app_id_key }}"
        pem_file="${RUNNER_TEMP}/bws/${{ inputs.app_pem_key }}.pem"
        output_file="${RUNNER_TEMP}/bws/GITHUB_APP_TOKEN"
        repo="${{ inputs.repo }}"
        python3 .github/scripts/github_app_token.py \
          --app-id-file "${app_id_file}" \
          --pem-file "${pem_file}" \
          --org "${{ inputs.github_org }}" \
          --repo "${repo}" \
          --output-file "${output_file}"
        if [ -n "${GITHUB_ACTIONS:-}" ]; then
          printf '%s\n' "::add-mask::$(cat "${output_file}")"
        fi

    - name: Store app token
      id: store-token
      shell: bash
      run: |
        set -euo pipefail
        token_file="${RUNNER_TEMP}/bws/GITHUB_APP_TOKEN"
        printf '%s\n' "GITHUB_APP_TOKEN_FILE=${token_file}" >> "$GITHUB_ENV"
        printf '%s\n' "github_app_token_file=${token_file}" >> "$GITHUB_OUTPUT"
