---
name: "dispatch-workflow"
description: "Dispatch workflow_dispatch events"
inputs:
  token:
    required: true
  owner:
    required: true
  repo:
    required: true
  workflow:
    required: true
  ref:
    required: true
  inputs:
    required: false
  inputs-path:
    required: false

runs:
  using: "composite"
  steps:
    - name: Dispatch
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        WORKFLOW: ${{ inputs.workflow }}
        REF: ${{ inputs.ref }}
        INPUTS: ${{ inputs.inputs }}
        INPUTS_PATH: ${{ inputs.inputs-path }}
      run: |
        set -euo pipefail
        python3 "${{ github.action_path }}/dispatch.py"
